version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app/
    ports:
      - "80:8000"
    env_file:
      - ./.env
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

